### ISSUE TITLE
Exception: Unknown site fedpkg

### ISSUE THREAD

**Issue by ignatenkobrain** [cgwalters/rpmdistro-gitoverlay#18]
```python
[ignatenko@ignatenko rpm-overlay]$ sudo docker run -v `pwd`:/srv --privileged -it --rm gitoverlay resolve
Running: git clone --mirror https://github.com/rpm-software-management/rpm /srv/src/https/github.com/rpm-software-management/rpm.tmp
Cloning into bare repository '/srv/src/https/github.com/rpm-software-management/rpm.tmp'...
remote: Counting objects: 123008, done.        
remote: Compressing objects: 100% (55/55), done.        
remote: Total 123008 (delta 25), reused 0 (delta 0), pack-reused 122953        
Receiving objects: 100% (123008/123008), 134.95 MiB | 8.81 MiB/s, done.
Resolving deltas: 100% (97380/97380), done.
Running: git config gc.auto 0
Running: git clone -q --no-checkout /srv/src/https/github.com/rpm-software-management/rpm /srv/src/_tmp/tmp-gitmirror0BtfOM/checkout
Running: git checkout -q -f e9e9b667795b749e63c41f53e55839ee6e8d8bbd
Running: git clone --mirror https://pkgs.fedoraproject.org/git/rpms/rpm /srv/src/https/pkgs.fedoraproject.org/git/rpms/rpm.tmp
Cloning into bare repository '/srv/src/https/pkgs.fedoraproject.org/git/rpms/rpm.tmp'...
remote: Counting objects: 3529, done.        
remote: Compressing objects: 100% (2600/2600), done.        
remote: Total 3529 (delta 1548), reused 2277 (delta 873)         
Receiving objects: 100% (3529/3529), 925.59 KiB | 673.00 KiB/s, done.
Resolving deltas: 100% (1548/1548), done.
Running: git config gc.auto 0
Running: git clone -q --no-checkout /srv/src/https/pkgs.fedoraproject.org/git/rpms/rpm /srv/src/_tmp/tmp-gitmirroreSv3gj/checkout
Running: git checkout -q -f 177601750a5c48d7e160274524f2e5721c2efede
Running: git clone -s --origin localmirror /srv/src/https/github.com/rpm-software-management/rpm /tmp/rdgo-srpmsColoCz/rpm
Cloning into '/tmp/rdgo-srpmsColoCz/rpm'...
done.
Running: git checkout -q e9e9b667795b749e63c41f53e55839ee6e8d8bbd
Running: git checkout -q -f HEAD
Running: git clone -s --origin localmirror /srv/src/https/pkgs.fedoraproject.org/git/rpms/rpm /tmp/rdgo-srpmsColoCz/distgit/rpm
Cloning into '/tmp/rdgo-srpmsColoCz/distgit/rpm'...
done.
Running: git checkout -q 177601750a5c48d7e160274524f2e5721c2efede
Running: git checkout -q -f HEAD
Running: tar --exclude-vcs -czf /tmp/rdgo-srpmsColoCz/distgit/rpm/rpm-rpm-4.13.0-alpha-224-e9e9b667795b749e63c41f53e55839ee6e8d8bbd.tar.gz --transform s,^rpm,rpm-rpm-4.13.0-alpha-224-e9e9b667795b749e63c41f53e55839ee6e8d8bbd, rpm
Traceback (most recent call last):
  File "/usr/lib64/rpmdistro-gitoverlay/rpkg-prep-sources", line 118, in <module>
    inst.run(sys.argv[1:])
  File "/usr/lib64/rpmdistro-gitoverlay/rpkg-prep-sources", line 84, in run
    rpkg = self._get_rpkg(opts.distgit_url, opts.distgit_co)
  File "/usr/lib64/rpmdistro-gitoverlay/rpkg-prep-sources", line 68, in _get_rpkg
    rpkg.do_imports(site=pkgtype)
  File "/usr/lib/python2.7/site-packages/pyrpkg/cli.py", line 143, in do_imports
    raise Exception('Unknown site %s' % site)
Exception: Unknown site fedpkg
Traceback (most recent call last):
  File "/usr/bin/rpmdistro-gitoverlay", line 66, in <module>
    main()
  File "/usr/bin/rpmdistro-gitoverlay", line 64, in main
    cmd[0]().run(sys.argv[1:])
  File "/usr/lib64/rpmdistro-gitoverlay/rdgo/task_resolve.py", line 362, in run
    srcsnap = self._generate_srcsnap(component)
  File "/usr/lib64/rpmdistro-gitoverlay/rdgo/task_resolve.py", line 299, in _generate_srcsnap
    srcsnap_name)
  File "/usr/lib64/rpmdistro-gitoverlay/rdgo/task_resolve.py", line 231, in _generate_srcsnap_impl
    '--lookaside-mirror='+self.lookaside_mirror])
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/lib64/rpmdistro-gitoverlay/rpkg-prep-sources', '--distgit-name=rpm', '--distgit-url=https://pkgs.fedoraproject.org/git/rpms/rpm', '--distgit-co=/tmp/rdgo-srpmsColoCz/distgit/rpm', '--lookaside-mirror=/srv/src/lookaside']' returned non-zero exit status 1
```

**Comment by ignatenkobrain** [comment]
```yaml
aliases:
  - name: github
    url: https://github.com/
    cacertpath: certs/DigiCertSHA2ExtendedValidationServerCA.pem

  - name: fedorapkgs
    url: https://pkgs.fedoraproject.org/git/rpms/
    cacertpath: certs/FedoraProjectCA.pem

distgit:
  prefix: fedorapkgs
  branch: master

root:
  mock: fedora-24-$arch

components:
  # TODO: add some freeze strategy
  - src: github:rpm-software-management/rpm
    distgit:
      branch: master
      patches: drop

  - src: github:openSUSE/libsolv
    freeze: 513c572b10e18bea5ac78709267de4b739cb31e7 # 0.6.20
    distgit:
      branch: master
      patches: drop
      freeze: 3be5091df898662f389f325f624740e5046e7ca0 # Plain 0.6.20

  - src: github:rpm-software-management/librepo
    freeze: 68724dc0364355b60e7ce7a23915f792215ba43e # 1.7.18
    distgit:
      branch: master
      patches: drop
      freeze: 98638e6d85170407acafeabf04d049eaa14226e7 # Plain 1.7.18

  - src: github:rpm-software-management/createrepo_c
    freeze: 7a74bb7dcb304521c115f9d5d773b4810e3513b2 # 0.10.0
    distgit:
      branch: master
      patches: drop
      freeze: 6ade1e9ac0a3053da4114445e1ab63e0a6b727e3 # Plain 0.10.0

  - src: github:rpm-software-management/libhif
    spec: internal
```
