### ISSUE TITLE
Allow for remote spec files

### ISSUE THREAD

**Issue by ashcrow** [cgwalters/rpmdistro-gitoverlay#46]
Currently `rpmdistro-gitoverlay` allows for either using a distgit for spec and lookaside **or** an ``internal`` location in the current repo for a spec file. However, there are some cases where the spec file may live outside of distgit and also not be in the source repo itself.

One way as noted by @cgwalters to implement this would be:

1. Add support multiple dist-gits
1. Avoid lookaside lookup when there is only a single `source0 `

**Comment by cgwalters** [comment]
The general thought I had was to support a model that worked more like Gentoo overlays as well as e.g. https://github.com/openembedded/openembedded-core (and somewhat like Android `repo`) where rather than the (IMO anti-pattern) of one git repo per spec, we'd have say:

```
specgit:
  url: github:coreos/specgit
  name: coreos
...

components:
  ignition:
    specgit: coreos
```

And that'd tell rdgo to look for `github.com/coreos/specgit/tree/ignition.spec` or so.
